version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5436:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080